---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.nginx.configMapName }}
  labels:
    app: {{ .Chart.Name }}
data:
  default.conf: |
    log_format logger-json '{"level": "debug", "ts": $msec, "status": $status, "method": "$request_method", "uri": "$request_uri",  "body_len": $body_bytes_sent, "req_len": $request_length, "resp_time": $request_time, "user_agent": "$http_user_agent"}';
    server {
      listen {{ .Values.service.port }};
      access_log /var/log/nginx/access.log logger-json;
      location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
      }
      location ~ ^/(products|categories|auth|orders) {
        proxy_pass {{ .Values.service.nginx.backendUrl }};
      }
      location /stub_status {
        allow 127.0.0.1;
        deny all;
        stub_status on;
      }
    }
